### ISSUE TITLE
TypeError: Messages.create() got an unexpected keyword argument 'tools'

### ISSUE THREAD

**Issue by yxl23** [Doriandarko/claude-engineer#122]
Author, why am I having this problem??? How do I need to solve it

D:\andconda\python.exe D:\下载\claude-engineer-main\claude-engineer-main\main.py 
┌────────────────────────────────── Welcome ──────────────────────────────────┐
│ Welcome to the Claude-3-Sonnet Engineer Chat with Multi-Agent and Image     │
│ Support!                                                                    │
└─────────────────────────────────────────────────────────────────────────────┘
Type 'exit' to end the conversation.
Type 'image' to include an image in your message.
Type 'automode ' to enter Autonomous mode with a specific number of iterations.
Type 'reset' to clear the conversation history.
Type 'save chat' to save the conversation to a Markdown file.
While in automode, press Ctrl+C at any time to exit the automode to return to 
regular chat.
You: automode
┌─ Automode ──────────────────────────────────────────────────────────────────┐
│ Entering automode with 25 iterations. Please provide the goal of the        │
│ automode.                                                                   │
└─────────────────────────────────────────────────────────────────────────────┘
┌─────────────────────────────────────────────────────────────────────────────┐
│ Press Ctrl+C at any time to exit the automode loop.                         │
└─────────────────────────────────────────────────────────────────────────────┘
You: 帮我用gradio来可视化一下yolov8的训练过程以及推理过程
Traceback (most recent call last):
  File "D:\下载\claude-engineer-main\claude-engineer-main\main.py", line 1198, in <module>
    asyncio.run(main())
  File "D:\andconda\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\andconda\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\andconda\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\下载\claude-engineer-main\claude-engineer-main\main.py", line 1169, in main
    response, exit_continuation = await chat_with_claude(user_input, current_iteration=iteration_count+1, max_iterations=max_iterations)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\下载\claude-engineer-main\claude-engineer-main\main.py", line 896, in chat_with_claude
    response = client.messages.create(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\andconda\Lib\site-packages\anthropic\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: Messages.create() got an unexpected keyword argument 'tools'

进程已结束，退出代码为 1

**Comment by jasonkneen** [comment]
Getting this too!

**Comment by elotech47** [comment]
Updating your antropic installation fixes this.
`pip install -U anthropic`

**Comment by jasonkneen** [comment]
I tried and didn't work but I think my conda / python setup was borked. I reset and restarted with a new env and rechecked settings etc and it worked.
