### ISSUE TITLE
Anthropic' object has no attribute 'beta'

### ISSUE THREAD

**Issue by friteuseb** [Doriandarko/claude-engineer#168]
Traceback (most recent call last):
  File "/home/cyril/ddev/claude-engineer/main.py", line 1249, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/cyril/ddev/claude-engineer/main.py", line 1246, in main
    response, _ = await chat_with_claude(user_input)
  File "/home/cyril/ddev/claude-engineer/main.py", line 924, in chat_with_claude
    response = client.beta.prompt_caching.messages.create(
AttributeError: 'Anthropic' object has no attribute 'beta'

**Comment by friteuseb** [comment]
since the last update i can't use the script, is it possible that claude beta features are not available in every country at the same time ?

**Comment by HashimSyedUBC** [comment]
I am still having this problem. Located in Canada.
